# Generated by Django 3.1.3 on 2020-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del Producto')),
                ('descripcion', models.TextField(verbose_name='Detalle del producto')),
                ('imagen', models.URLField(verbose_name='Url de la Imagen')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('estaEnOferta', models.BooleanField(default=False, verbose_name='Esta en Oferta?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
