# Generated by Django 3.1.3 on 2020-11-12 16:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20201112_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Detalle del producto'),
        ),
    ]
